MODEL:
  BACKBONE: convnext_tiny_hnf       # convnext_tiny_hnf
  ACT_LAYER: silu
  NORM_LAYER: bn
  POOLING: false
  EMBEDDING_DIM: 512
  LOSS: partial_fc
  NUM_CLASS: 360232
  SAMPLE_RATE: 0.3


DATASET:
  TYPE: glint360k
  TRAIN: /mnt/ssd/qiujing/glint360k
  VAL: /mnt/ssd/qiujing/glint360k
  VAL_TARGETS:
  - lfw
  - cfp_fp
  - agedb_30
  TEST: ''
  IMG_SIZE: 112
  NUM_IMAGES: 17091657
  TRANSFORM:
    RandomResizedCrop: 0.5
    HorizontalFlip: 0.5
    RandomBrightnessContrast: 0.5
    
SOLVER:
  OPTIM: sgd
  BATCH_SIZE_PER_GPU: 256
  BASE_LR: 0.1
  WARMUP_EPOCH: 2
  NUM_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  LR_SCHEDULER_NAME: cosine
  FP16: false
  LOGGER_STEP: 100
  VAL_STEP: 200
OUTPUT: runs/CosFace_convnext_s0.3_l0.1
NUM_WORKERS: 4
