MODEL:
  BACKBONE: 'convnext_base_in22ft1k'
  ACT_LAYER: 'silu'
  NORM_LAYER: 'bn'
  POOLING: False
  EMBEDDING_DIM: 512
  LOSS: 'partial_fc_adaface'
  NUM_CLASS: 360232
  SAMPLE_RATE: 0.1

DATASET:
  TYPE: 'glint360k'  # 'folder'
  TRAIN: '/dataset/dataset/glint360k/glint360k'
  VAL: '/dataset/dataset/glint360k/glint360k'
  VAL_TARGETS: ['lfw', 'cfp_fp', "agedb_30"]
  IMG_SIZE: 112
  NUM_IMAGES: 17091657
  TRANSFORM:
    RandomResizedCrop: 0.5
    HorizontalFlip: 0.5
    RandomBrightnessContrast: 0.5

SOLVER:
  OPTIM: 'sgd'
  BATCH_SIZE_PER_GPU: 64
  BASE_LR: 0.4
  WARMUP_EPOCH: 2
  NUM_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  LR_SCHEDULER_NAME: 'cosine'
  FP16: False
OUTPUT: 'runs'
NUM_WORKERS: 8
